language: ruby
rvm:
  - 2.0.0
before_script:
  - "cp config/database.example.yml config/database.yml"
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
